#!/usr/bin/env bash
# Smoke test for bench/lib/generate-recipe-help.sh and docs/RECIPE-COMMANDS.md.
# Run: ./bench/tests/test-recipe-help.sh
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
GENERATOR="$REPO_ROOT/bench/lib/generate-recipe-help.sh"
DOC="$REPO_ROOT/docs/RECIPE-COMMANDS.md"

pass=0
fail=0

check() {
  local desc="$1"; local result="$2"
  if [ "$result" = "0" ]; then
    echo "ok - $desc"
    pass=$((pass + 1))
  else
    echo "FAIL - $desc"
    fail=$((fail + 1))
  fi
}

TMP="$(mktemp)"
"$GENERATOR" --out "$TMP" >/dev/null
[ -s "$TMP" ]
check "generator writes non-empty output" "$?"

grep -q "generated by bench/lib/generate-recipe-help.sh" "$TMP"
check "output contains generator banner comment" "$?"

grep -q "recipe-plan-phase" "$TMP"
check "output lists recipe-plan-phase" "$?"

grep -q "recipe-help" "$TMP"
check "output lists recipe-help" "$?"

grep -q "| planned |" "$TMP"
check "output marks planned capabilities (e.g. recipe-new-project/onboard)" "$?"

grep -q "Native GSD commands" "$TMP"
check "output includes native GSD section" "$?"

grep -q "Bench runners" "$TMP"
check "output includes bench runners section" "$?"

grep -q "Field benchmarks" "$TMP"
check "output includes field benchmarks section" "$?"

grep -q "KAN-53" "$TMP"
check "output includes KB-Evaluations benchmark row" "$?"

rm -f "$TMP"

[ -f "$DOC" ]
check "committed docs/RECIPE-COMMANDS.md exists" "$?"

TMP_CAP="$(mktemp)"
trap 'rm -f "$TMP_CAP"' EXIT
"$REPO_ROOT/bench/lib/capability-schema.sh" generate-capability --target "$REPO_ROOT" --out "$TMP_CAP" >/dev/null
python3 -c "
import json
doc = open('$DOC').read()
caps = json.load(open('$TMP_CAP'))['capabilities']
for c in caps:
    name = c.get('invoke_name')
    if name:
        assert name in doc, f'missing invoke_name {name} in RECIPE-COMMANDS.md'
"
check "every catalog invoke_name appears in docs/RECIPE-COMMANDS.md" "$?"

echo "---"
echo "$pass passed, $fail failed"
[ "$fail" = "0" ]
